### ISSUE TITLE
Readme on how to get this running

### ISSUE THREAD

**Issue by dzoba** [geneshuman/pure_morph#1]
I would like to try running this myself but the lack of instruction makes it difficult.

I tried giving it a shot with ```bower i``` but ran into a problem with this line: https://github.com/geneshuman/pure_morph/blob/master/bower.json#L19

Thanks!

**Comment by geneshuman** [comment]
Hey, thanks for your interest in my project!  I've fixed the issue you ran
into, and put a few brief instructions in a readme.  If you have any more
issues, don't hesitate to contact me.

Regards,
=Gene

PS, I've recently recovered from a particularly nasty illness, and should
be a bit more responsive now.
